<definitions
     name="procedureAdapter"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/procedure/" 
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/procedure/"   
     xmlns="http://schemas.xmlsoap.org/wsdl/" >

    <types>
        <schema attributeFormDefault="qualified" elementFormDefault="qualified" 
                targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/procedure/"
                xmlns="http://www.w3.org/2001/XMLSchema" 
                xmlns:PROCEDUREAPP="http://xmlns.oracle.com/pcbpel/adapter/procedure/">
          <element name="ProcedureHeaderType">
                <complexType>
                    <sequence>
                        <element name="Username" type="string"/>
                        <element name="Responsibility" type="string"/>
                    </sequence>
                </complexType>
            </element> 
        </schema>
    </types>
   
    <!-- Header Message --> 
    <message name="Header_msg"> 
      <part element="tns:ProcedureHeaderType" name="Header"/> 
   </message> 

</definitions>