<%@ page language="java" %>
<%@ page errorPage="errorpage.jsp" %>
<%@ page import="oracle.jbo.ApplicationModule, oracle.jbo.JboException" %>
<%@ page import="oracle.jbo.html.*" %>
<%@ taglib  uri="/webapp/DataTags.tld"  prefix="jbo" %>
<%-- This JSP component handles all events issued in the JSP application.
     It is called by the DataHandler tag --%>
<%
   // Retrieve all request parameters using our routine to handle multipart encoding type
   RequestParameters params = HtmlServices.getRequestParameters(pageContext);

   String amId = params.getParameter("amId");
   // This parameter is always generated by UrlEvent or FormEvent
   // It contains the name of the ViewObject bind to the datasource on which
   // the event need to be applied.
   String voName = params.getParameter("jboEventVo");
%>
<% // Not all event contain a ViewObject name (Commit and Rollback don't)
   // The next block of events are handled only when the ViewObject name is available
   if (voName != null)
   { %>
<%-- Restore the binding to the datasource, using the appId and the ViewObject name --%>
<jbo:DataSource id="ds" appid="<%=amId%>" viewobject="<%=voName%>" />

<%-- DML event handling (Create handling is embeded in  DataEditComponent)--%>
<jbo:OnEvent name="update">
   <jbo:Row id="myrow" datasource="ds" rowkeyparam="jboRowKey" action="Update" />
</jbo:OnEvent>

<jbo:OnEvent name="create">
   <jbo:Row id="newrow" datasource="ds" action="CreateInRange" ><%
   try
   { %>
      <jbo:SetAttribute dataitem="*" /><%
   } catch (JboException ex)
   {
      newrow.remove();
      throw ex;
   } %>
   </jbo:Row>
</jbo:OnEvent>

<jbo:OnEvent name="delete">
   <jbo:Row id="delrow" datasource="ds" rowkeyparam="jboRowKey" action="Delete" />
</jbo:OnEvent>

<%-- Scroll event handling 
     RowsetNavigate retrieve the action from its parent tag current event name --%>
<jbo:OnEvent list="firstSet, nextSet, previousSet, lastSet, gotoSet">
   <jbo:RowsetNavigate datasource="ds" />
</jbo:OnEvent>

<%-- Navigation event handling 
     RowsetNavigate retrieve the action from its parent tag current event name --%>
<jbo:OnEvent list="first, next, previous, last">
   <jbo:RowsetNavigate datasource="ds" />
</jbo:OnEvent>

<%-- Query event handling (issued from the DataQueryComponent)
     The handling consist of modifying the ViewCriterias --%>
<jbo:OnEvent name="Del Criteria" >
   <% 
      String remove = params.getParameter("index"); 
      String removeId = "row" + remove;
   %>
   <jbo:ViewCriteria id="vc" datasource="ds" action="append">
      <jbo:CriteriaRow id="<%=removeId%>" index="<%=remove%>" clearall="true" />
   </jbo:ViewCriteria>
</jbo:OnEvent>

<jbo:OnEvent name="Clear All" >
   <jbo:ViewCriteria id="vc" datasource="ds" action="new" />
</jbo:OnEvent>

<jbo:OnEvent list="Search, Add Criteria" >
   <% String rowParam = params.getParameter("nRows");
      int nRows = 0;
      if (rowParam != null)
      {
         try { nRows = Integer.parseInt(rowParam); }
         catch (Exception ex) { }
      }
   %>   
   <jbo:ViewCriteria id="vc" datasource="ds" action="new">
   <% for (int index=0; index < nRows; index++)
      { 
         String criteriaRowId = "row" + index;
   %>
      <jbo:CriteriaRow id="<%=criteriaRowId%>" >
         <jbo:AttributeIterate id="attrvc" datasource="ds" queriableonly="true">
            <% String item = attrvc.getName();
               String value = params.getParameter("row" + index + "_" + item); %>
            <jbo:Criteria dataitem="<%=item%>" value="<%=value%>" />
         </jbo:AttributeIterate>
      </jbo:CriteriaRow>
   <% } %>
   </jbo:ViewCriteria>
</jbo:OnEvent>

<% }%>

<%-- Transaction event handling --%>
<jbo:OnEvent name="Commit" >
   <jbo:Commit appid="<%=amId%>" />
</jbo:OnEvent>

<jbo:OnEvent name="Rollback" >
   <jbo:RollBack appid="<%=amId%>" />
</jbo:OnEvent>



